### ISSUE TITLE
do not auto scroll to bottom up reconnect

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [glowing-bear/glowing-bear-cordova#16]
Sometimes the Internet connection is unstable and every time glowing-bear reconnects, it scrolls to bottom of the buffer, which is very disruptive while reading messages.

**Comment by lorenzhs** [comment]
This isn't specific to the cordova wrapper, so would probably be more appropriate in the main GB repo. We would definitely welcome a pull request to GB that would fix this, though.
